weecology/ogrants

_grants/treddenick_andrew_2011.md, _grants/treddenick_andrew_2014.md
just small edit to the year field for my proposals. Thanks for doing this @ethanwhite!
=> update tredennick proposal years

_authors/carrasco_john_joseph.md, _grants/carrasco_jj_2014.md
Successfully funded ERC grant for theoretical physics.  Link to figshare containing original proposal and pdf for requisite round 2 panel presentation.
=> added 2014 erc & author (jjmc)

_includes/sort.html, index.md, public/css/hyde.css
Mostly stylistic changes. 
* allow table to be sorted
* linked to font awesome for the sort icon
* changed width of content in hyde.css (lots of whitespace)
Feel free to incorporate or ignore whatever aspects suit you. 
The website is a really great idea and useful resource!
Cheers.
=> sortable table

_authors/chabert_steren.md, _authors/doran_michael.md, _authors/klein_arno.md, _authors/leese_florian.md, _authors/mietchen_daniel.md, _authors/robinson_amy.md, _authors/schmelling_nicolas.md, _authors/toro_roberto.md, _authors/vanderhoeven_sonia.md, _grants/chabert_steren_2017.md, _grants/doran_michael_2016.md, _grants/kissling_daniel_2017.md, _grants/klein_arno_2013.md, _grants/klein_arno_2016a.md, _grants/klein_arno_2016b.md, _grants/klein_arno_2016c.md, _grants/klein_arno_2016d.md, _grants/klein_arno_2016e.md, _grants/klein_arno_2016f.md, _grants/leese_florian_2016.md, _grants/mietchen_daniel_2015.md, _grants/robinson_amy_2016.md, _grants/schmelling_nicolas_2017.md, _grants/vanderhoeven_sonia_2017.md
Nine additional people, fifteen additional grant proposals, all from RIO.
Note, one from Chile and one from Australia. Not just a US-EU thing 😃
=> more from RIO

_grants/redfield_rosie_2012a.md, _grants/redfield_rosie_2012b.md, _grants/redfield_rosie_2012c.md
These are the YAMLs for the grants listed in issue #19
=> Adding Rosie Redfield grants

_grants/verbruggen_heroen_2013.Rmd, _grants/verbruggen_heroen_2015a.Rmd, _grants/verbruggen_heroen_2015b.Rmd
=> Add additional Heroen Verbruggen grants

_grants/jensen_jan_2015.md
"High Througput pKa Prediction Using Semi Empirical Methods" grant from Jan H Jensen
=> jensen_jan_2015.md

_authors/evans_michelle.md, _grants/evans_michelle_2014.md, _grants/evans_michelle_2015.md
Add two grants (evans_michelle_2014.md and evans_michelle_2015.md) and author info (evans_michelle.md)
=> Mvevans89 patch 1

_grants/wright_april_2013.md
RIP DDIG, but I imagine a lot of departments and societies will still offer ddig-likes.
=> adding funded ddig for wright

_authors/ball_mad.md, _grants/ball_mad_2017.md
Add Mad Price Ball's (@madprime) funded Shuttleworth Foundation Fellowship.
On personal, but stable website.
=> Add Mad Ball - Shuttleworth 2017 - Funded

_authors/fan_jean.md, _grants/fan_jean_2013.md, _grants/fan_jean_2015.md
Dear Ethan,
Thanks for creating and maintaining this excellent resource. I've taken the liberty to add the information for 2 of my public grants - an NSF GRFP and an NIH F31 - both of which are hosted on my website in full along with all supporting documents including cover letters and reviewer responses / summary statements. 
I figured it would be easier to make the edits and use a pull request rather than creating an issue and emailing you about the edits. 
All the best,
Jean
=> add grants

_authors/pulliam_juliet.md, _grants/pulliam_juliet_2012.md
Adding proposal for the International Clinics in Infectious Disease Dynamics and Data (ICI3D) Program (NIH award number R25GM102149)
=> Submitting a grant for inclusion

_grants/howison_james_2016.md, _grants/piwowar_heather_2013.md, _grants/piwowar_heather_2018.md, _grants/priem_jason_2013.md
=> Add new Impactstory grants

Gemfile.lock, _authors/moritz_mark.md, _grants/moritz_mark_1999.md, _grants/moritz_mark_2008.md, _grants/moritz_mark_2012.md, _grants/moritz_mark_2015.md, atom.xml
Plus a couple of tiny site updates
=> Add four grants by Mark Moritz

_includes/add_form.html, add.md
Uses netlify's forms to store and notify.
=> Allow submitting new grants via a webform

.travis.yml, tests/validate_links.py
=> add link validation

_grants/brown_ctitus_2007.md, _grants/brown_ctitus_2009.md, _grants/brown_ctitus_2010.md, _grants/brown_ctitus_2011.md, _grants/brown_ctitus_2012a.md, _grants/brown_ctitus_2012b.md, _grants/brown_ctitus_2012c.md, _grants/brown_ctitus_2012d.md, _grants/brown_ctitus_2014.md
I referred to these a lot when I was writing grants a lot when I was writing a proposal for an NIH R25 training grant. Hopefully, more people will continue to use them now that the links are updated.
closes https://github.com/weecology/ogrants/issues/87
=> update @ctb links

_layouts/grant.html
=> Don't display ORCID link when no ORCID

_authors/daniel_himmelstein.md, _grants/daniel_himmelstein_2018.md
https://doi.org/10.6084/m9.figshare.9931367
=> Sloan Manubot grant to UPenn/Himmelstein

README.md, about.md, add.md
One sentence per line
Add Travis CI badge
@ethanwhite did you want to review my PRs (or should I proceed without review at my discretion)?
=> Lint markdown files

add.md
=> Add note about hand processing taking time

_layouts/grant.html, index.md
solves #92 
e.g. https://www.ogrants.org/grants/johnson_lisa_2016.html
=> add status display for nonmatching values

_includes/sidebar.html, about.md, add.md, advisors-meeting-agenda.md, advisors.md, call-for-participation.md, grants-01-all.md, grants-02-funders.md, grants-03-programs.md
=> only include some pages in sidebar

_grants/brown_ctitus_2012e.md
Fixes https://github.com/ogrants/ogrants/issues/179
=> add R25 renewal per request

README.md
No need to link to the repository since the README is in the repo.
Fixes #197
=> Cleanup copy-paste liquid in README

_grants/formoso_jesica_2025.md
Hello, thank you for allowing us to publish our proposal. We suggest some changes in this pull request.
=> Update and rename formosa_jesica_2025.md to formoso_jesica_2025.md
